services:
  postgres:
    image: "postgres:16.1-alpine3.19"
    env_file: ".env"
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    restart: unless-stopped

volumes:
  redis_data:
