-- AlterTable
ALTER TABLE "Availability" ADD COLUMN     "duration" SMALLINT NOT NULL DEFAULT 60,
ADD COLUMN     "isVisible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lunchTimeEnd" SMALLINT NOT NULL DEFAULT 780,
ADD COLUMN     "lunchTimeStart" SMALLINT NOT NULL DEFAULT 720;
